### PR TITLE
693 negative iso transparency

### LINKED ISSUE #693: surface repr: opacity does not work with neglateIsolevel
Hi, please try with the .cube file in this https://github.com/arose/nglview/files/3579869/input.zip
- load it to http://nglviewer.org/ngl/
- With the surface repr, click "neglateIsolevel" and then adjust the "Opacity". There is no effect.

Here is the original context: https://github.com/arose/nglview/issues/785#issuecomment-528413612

thanks and cheers

### PR DESCRIPTION
**Pull request by fredludlow**
I think this finally fixes #693. Triangle orders and normal vertices are flipped when contouring at a negative level.

Demo here:
https://fredludlow.com/ngl/fix-693/examples/webapp.html?script=test/negative-iso

Built file available here:
https://fredludlow.com/ngl/fix-693/build/js/ngl.dev.js

### CODE REVIEW

File: src/surface/marching-cubes.ts [hunk 1]
```diff
@@ -744,8 +751,8 @@ function MarchingCubes (this: MarchingCubes, field: number[], nx: number, ny: nu
         }
       } else {
         // FIXME normals flipping (see above) and vertex order reversal
```
Comment (garyo) [inline src/surface/marching-cubes.ts:753]: This looks great, thanks Fred! I think you could delete this FIXME comment with this fix.

**Review by garyo — APPROVED** [review]
LGTM!

File: src/surface/marching-cubes.ts (hunk 1 above)
Comment (fredludlow) [reply src/surface/marching-cubes.ts]: Done! Thanks
